### ISSUE TITLE
git dep preparation failed

### ISSUE THREAD

**Issue by piranna** [nearform/node-test-github-reporter#113]
https://github.com/nearform/node-test-github-reporter/blob/46eaf4c46b138eb4c5b6a1832a59136d2bc09f4e/package.json#L33

Install fails me due to the usage of this git dependency, please publish the package in npm and use it as dependency, instead of as git dependency.

**Comment by simoneb** [comment]
What error are you getting?

**Comment by piranna** [comment]
> What error are you getting?

Error message is `git dep preparation failed`, this is the only package that generates this error, if I remove it install works fine, and if I install it alone, install would fail too, and the only git dependency it has is `node-test-parser`:

```console
[piranna@executive:~/github/Mafalda/Mediasoup-cluster-CLI]
1 (main) > npm install --no-save --verbose node-test-github-reporter
npm verb cli /usr/bin/node /usr/bin/npm
npm info using npm@10.1.0
npm info using node@v20.8.0
npm verb title npm install node-test-github-reporter
npm verb argv "install" "--no-save" "--loglevel" "verbose" "node-test-github-reporter"
npm verb logfile logs-max:10 dir:/home/piranna/.npm/_logs/2023-10-08T18_38_09_626Z-
npm verb logfile /home/piranna/.npm/_logs/2023-10-08T18_38_09_626Z-debug-0.log
npm verb shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
npm http fetch GET 200 https://registry.npmjs.org/node-test-github-reporter 19ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@actions%2fcore 11ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/stack-utils 11ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/error-stack-parser 13ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/uuid 8ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@actions%2fhttp-client 10ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/stackframe 10ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/escape-string-regexp 8ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/tunnel 3ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/undici 3ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@fastify%2fbusboy 3ms (cache hit)
npm http fetch GET 200 https://codeload.github.com/nearform/node-test-parser/tar.gz/229b95e38d9a021230a83d7a89e344965b3ba1fb 643ms (cache revalidated)
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 1322ms
npm http fetch GET 200 https://registry.npmjs.org/minimist 3ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/optimist 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/package-json-validator 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/eslint-plugin-package-json 843ms (cache revalidated)
npm verb stack Error: git dep preparation failed
npm verb stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
npm verb stack     at ChildProcess.emit (node:events:514:28)
npm verb stack     at maybeClose (node:internal/child_process:1105:16)
npm verb stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm verb cwd /home/piranna/github/Mafalda/Mediasoup-cluster-CLI
npm verb Linux 6.2.0-25-generic
npm verb node v20.8.0
npm verb npm  v10.1.0
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/piranna/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! > node-test-parser@2.1.0 prepare
npm ERR! > husky install
npm ERR! npm verb cli /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js
npm ERR! npm info using npm@10.1.0
npm ERR! npm info using node@v20.8.0
npm ERR! npm verb title npm install
npm ERR! npm verb argv "install" "--force" "--cache" "/home/piranna/.npm" "--prefer-offline" "false" "--prefer-online" "false" "--offline" "false" "--no-progress" "--no-save" "--no-audit" "--include" "dev" "--include" "peer" "--include" "optional" "--no-package-lock-only" "--no-dry-run"
npm ERR! npm verb logfile logs-max:10 dir:/home/piranna/.npm/_logs/2023-10-08T18_38_17_771Z-
npm ERR! npm verb logfile /home/piranna/.npm/_logs/2023-10-08T18_38_17_771Z-debug-0.log
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! husky - .git can't be found (see https://typicode.github.io/husky/#/?id=custom-directory)
npm ERR! npm verb stack Error: command failed
npm ERR! npm verb stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
npm ERR! npm verb stack     at ChildProcess.emit (node:events:514:28)
npm ERR! npm verb stack     at maybeClose (node:internal/child_process:1105:16)
npm ERR! npm verb stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm ERR! npm verb pkgid node-test-parser@2.1.0
npm ERR! npm verb cwd /home/piranna/.npm/_cacache/tmp/git-cloneEQ42qb
npm ERR! npm verb Linux 6.2.0-25-generic
npm ERR! npm verb node v20.8.0
npm ERR! npm verb npm  v10.1.0
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /home/piranna/.npm/_cacache/tmp/git-cloneEQ42qb
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c husky install
npm ERR! npm verb exit 1
npm ERR! npm verb code 1
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in: /home/piranna/.npm/_logs/2023-10-08T18_38_17_771Z-debug-0.log
npm verb exit 1
npm verb unfinished npm timer reify 1696790289734
npm verb unfinished npm timer reify:audit 1696790296942
npm verb unfinished npm timer reify:unpack 1696790296949
npm verb unfinished npm timer reifyNode:node_modules/node-test-parser 1696790296950
npm verb unfinished npm timer auditReport:init 1696790298269
npm verb unfinished npm timer metavuln:calculate:security-advisory:@mafalda-sfu/eslint-config:CHPaasZodQWY+ND+r8ECIpis9chZYeG/oqNmJJ6KN93ERa/s5y4LQpUlB1JtnV6NNBsfIfDkM2503j3e0CNG/w== 1696790299126
npm verb unfinished npm timer metavuln:packument:@mafalda-sfu/eslint-config 1696790299126
npm verb code 1

npm ERR! A complete log of this run can be found in: /home/piranna/.npm/_logs/2023-10-08T18_38_09_626Z-debug-0.log
```

**Comment by msebastianb** [comment]
Hello @piranna, we released the v1.1.6 which uses the node-test-parser from npm, please let us know if the problem persists.

**Comment by piranna** [comment]
> Hello @piranna, we released the v1.1.6 which uses the node-test-parser from npm, please let us know if the problem persists.

It's working fine now, thanks :-)

**Comment by prajwal000** [comment]
how did you soly it @piranna
